animals=["lion","tiger","elephant"]
animals.append("rhinos")
print(animals)
animals.clear()
print(animals)
x=animals.copy()
print(x)
vegetables=["potato","tomato","ginger"]
x=vegetables.count("tomato")
print(x)
animals.extend(vegetables)
print(animals)
x=vegetables.index("ginger")
print(x)
vegetables.pop(1)
print(vegetables)
vegetables.insert(1,"carrot")
print(vegetables)

vegetables.reverse()
print(vegetables)

vegetables.remove("potato")
print(vegetables)
vegetables.sort()
print(vegetables)
