string1="There Are 50 Animals."
x=string1.capitalize()
print(x)
x=string1.casefold()
print(x)
string2="dogs20"
x=string2.center(20,"O")
print(x)
string3="exercise is good for health,its good for our apetite."
x=string3.count("good")
print(x)
x=string1.encode()
print(x)
x=string3.endswith(".")
print(x)
string4="u/T/#o/*"
x=string4.expandtabs(2)
print(x)
x=string3.find("health")
print(x)
string5 = "For only {price:.2f} ruppees!"
print(string5.format(price = 20))
x=string3.index("apetite")
print(x)
x=string2.isalnum()
print(x)
x=string1.isalpha()
print(x)
x=string3.isascii()
print(x)
string6="\u0033"
x=string6.isdecimal()
print(x)
string7="8900"
x=string7.isdigit()
print(x)
x=string2.isidentifier()
print(x)
x=string2.islower()
print(x)
x=string7.isnumeric()
print(x)
x=string1.isspace()
print(x)
x=string1.istitle()
print(x)
x=string6.isprintable()
print(x)
x=string2.isupper()
print(x)
tuple=("dog","cat","pig")
x="-".join(tuple)
print(x)
string8="lion"
x=string8.ljust(20)
print(x,"is the king of the jungle")
x=string1.lower()
print(x)
x=string8.lstrip()
print("of all animals",x,"is the strongest")
mytable=string1.maketrans("S","P")
print(string1.translate(mytable))
x=string3.partition("health")
print(x)
x=string3.replace("health","life")
print(x)
x=string1.rfind("Animals")
print(x)
x=string1.rindex("Animals")
print(x)
x=string8.rjust(20)
print(x,"is my favourite animal")
x=string3.rpartition("health")
print(x)

x=string3.rpartition(",")
print(x)
x=string8.rstrip()
print("of all animals",x,"is the strongest")
x=string1.split()
print(x)
x=string1.swapcase()
print(x)
x=string3.title()
print(x)
mydict = {83:  80}
txt = "Hello nebin!"
print(txt.translate(mydict))
x=string3.upper()
print(x)
x=string7.zfill(10)
print(x)
